"""create projects

Revision ID: 44bac9bda549
Revises: 91b0a2eb63a5
Create Date: 2026-09-26 19:02:52.637425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44bac9bda549'
down_revision: Union[str, Sequence[str], None] = '91b0a2eb63a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_company', 'projects', ['company_id'], unique=False)
    op.create_index('ix_accounts_company', 'accounts', ['company_id'], unique=False)
    op.create_index('ix_categories_company_group', 'categories', ['company_id', 'group_id'], unique=False)
    op.create_index('ix_category_groups_company', 'category_groups', ['company_id'], unique=False)
    op.create_index(op.f('ix_tokens_token_hash'), 'tokens', ['token_hash'], unique=True)
    op.add_column('transactions', sa.Column('project_id', sa.Uuid(), nullable=True))
    op.create_index('ix_transactions_account_date', 'transactions', ['account_id', 'occurred_at'], unique=False)
    op.create_index('ix_transactions_category', 'transactions', ['category_id'], unique=False)
    op.create_index('ix_transactions_project', 'transactions', ['project_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('ix_transactions_project', table_name='transactions')
    op.drop_index('ix_transactions_category', table_name='transactions')
    op.drop_index('ix_transactions_account_date', table_name='transactions')
    op.drop_column('transactions', 'project_id')
    op.drop_index(op.f('ix_tokens_token_hash'), table_name='tokens')
    op.drop_index('ix_category_groups_company', table_name='category_groups')
    op.drop_index('ix_categories_company_group', table_name='categories')
    op.drop_index('ix_accounts_company', table_name='accounts')
    op.drop_index('ix_projects_company', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
