"""create subscriptions

Revision ID: a90a705fc986
Revises: 44bac9bda549
Create Date: 2026-09-28 14:33:01.429247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a90a705fc986'
down_revision: Union[str, Sequence[str], None] = '44bac9bda549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.Enum('free', 'pro', name='subscription_plan'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'canceled', 'expired', name='subscription_status'), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.execute('ALTER TYPE categoryiconcolor RENAME TO category_icon_color')
    op.create_index(op.f('ix_subscriptions_provider_payment_id'), 'subscriptions', ['provider_payment_id'], unique=True)
    op.create_index('ix_subscriptions_user', 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscriptions_user', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_provider_payment_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
