"""alter token_hash

Revision ID: e828dfca91b4
Revises: 6e2e8e13fb3b
Create Date: 2026-09-28 21:26:14.836126

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'e828dfca91b4'
down_revision: str | Sequence[str] | None = '6e2e8e13fb3b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
